import type { Metadata } from "next";
import { Footer } from "@/components/footer";
import { Navigation } from "@/components/navigation";

export const metadata: Metadata = { title: "Privacy Policy", alternates: { canonical: "/privacy" } };

export default function PrivacyPage() {
  return (
    <>
      <Navigation />
      <main id="top" className="px-6 py-20">
        <article className="mx-auto max-w-3xl">
          <p className="text-sm font-semibold text-primary">Legal</p>
          <h1 className="heading mt-4 text-5xl">Privacy Policy</h1>
          <p className="mt-6 leading-8 text-slate-600">Nexra AI collects only the information needed to respond to inquiries, operate our products, and improve service reliability. If you contact us by email, we use your message and contact details to reply and maintain the business relationship you requested.</p>
          <h2 className="heading mt-10 text-3xl">Information we process</h2>
          <p className="mt-4 leading-8 text-slate-600">We may process contact details, product interest, support context, and basic technical data such as device, browser, and usage signals generated by our website or products.</p>
          <h2 className="heading mt-10 text-3xl">How we use information</h2>
          <p className="mt-4 leading-8 text-slate-600">We use information to provide requested services, communicate about Nexra AI products, protect our systems, comply with legal obligations, and make product experiences clearer and more dependable.</p>
          <h2 className="heading mt-10 text-3xl">Contact</h2>
          <p className="mt-4 leading-8 text-slate-600">For privacy questions, contact <a className="font-semibold text-primary" href="mailto:hello@nexra.ai">hello@nexra.ai</a>.</p>
        </article>
      </main>
      <Footer />
    </>
  );
}
